experiment_name: asearcher-qwn3-8b-duckduckgo-debug
trial_name: run1

cluster:
  fileroot: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-mtsearch-assistant/ai-search/yanghaocheng04/ASearcher/experiments
  n_nodes: 1
  n_gpus_per_node: 8
  name_resolve:
    type: nfs
    nfs_record_root: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-mtsearch-assistant/ai-search/yanghaocheng04/ASearcher/name_resolve
seed: 1
total_train_epochs: 1  # Just 1 epoch for testing
total_train_steps: null
tokenizer_path: ${actor.path}
# Reduced allocation for debugging: 2 GPUs for SGLang, 2 for training
allocation_mode: sglang.d2p1t1+d2p1t1
async_training: true

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 16  # Much smaller for debugging
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 4
  enable_rollout_tracing: true
  setup_timeout: 300.0  # Increased timeout to 5 minutes

gconfig:
  n_samples: 2  # Minimal samples for testing
  min_new_tokens: 0
  max_new_tokens: 512  # Reduced from 1024
  greedy: false
  temperature: 1.0

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-mtsearch-assistant/ai-search/deepsearch_files/LLMbasemodels/huggingface.co/Qwen/Qwen3-8B
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 4000  # Reduced from 8000
  optimizer:
    type: adam
    lr: 5e-6
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  backend: fsdp

  group_size: ${gconfig.n_samples}
  group_adv_norm: false
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  log_agent_stats: true
  log_agent_stats_keys: 
    - num_input_tokens
    - num_output_tokens
    - num_llm_gens
    - num_search_queries
    - num_success_search_queries
    - num_failed_search_queries
    - num_pages
    - num_success_url_accesses
    - num_failed_url_accesses
    - score
    - judge_q_invalid
    - format_reward

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 16384  # Reduced from 32768
  optimizer: null
  backend: fsdp

# SGLang - Reduced memory settings
server_only: false
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: false
  dtype: ${actor.dtype}
  max_running_requests: 8  # Limited concurrent requests
  context_length: 8192  # Reduced from 32768
  mem_fraction_static: 0.8  # Reduced from 0.9
  attention_backend: fa3
  setup_timeout: 300.0  # 5 minutes timeout

# datasets
train_dataset:
  batch_size: 8  # Very small batch for debugging
  shuffle: true
  pin_memory: false  # Disabled for debugging
  path: train_data/ASearcher-Base-35k.jsonl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 10
  freq_secs: 3600

checkpointer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: offline  # Offline for debugging

# Launcher
launcher:
  inference_server_cpus_per_gpu: 15
  inference_server_mem_per_gpu: 153600
  trainer_cpus_per_gpu: 15
  trainer_mem_per_gpu: 153600


# ASearcher specific parameters - Minimal for debugging
max_turns: 8  # Reduced from 32
n_trajs: 2  # Minimal trajectories
search_client_type: async-duckduckgo-search
reward_type: F1
topk: 3  # Reduced from 5
valid_inst_ratio: 0.3